"""delist guard: consecutive_misses, scan source_counts

Revision ID: d01496d3604b
Revises: 7980ad450dea
Create Date: 2026-08-22 23:07:02.694860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01496d3604b'
down_revision: Union[str, Sequence[str], None] = '7980ad450dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_logs', sa.Column('source_counts', sa.Text(), nullable=True))
    # server_default because the table is populated: a bare NOT NULL add fails.
    op.add_column(
        'scraped_listings',
        sa.Column('consecutive_misses', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_listings', 'consecutive_misses')
    op.drop_column('scan_logs', 'source_counts')
    # ### end Alembic commands ###
