"""case evidence snapshot, model version, resolution codes

Revision ID: d80ad4b1cb91
Revises: d01496d3604b
Create Date: 2026-08-23 09:24:19.748633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80ad4b1cb91'
down_revision: Union[str, Sequence[str], None] = 'd01496d3604b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('evidence_snapshot', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('opening_evidence', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('prompt_version', sa.String(length=32), nullable=True))
    op.add_column('cases', sa.Column('resolution_code', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'resolution_note')
    op.drop_column('cases', 'resolution_code')
    op.drop_column('cases', 'prompt_version')
    op.drop_column('cases', 'model_name')
    op.drop_column('cases', 'opening_evidence')
    op.drop_column('alerts', 'evidence_snapshot')
    # ### end Alembic commands ###
