import { zodResolver } from "@hookform/resolvers/zod";
import { Home, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { PropertyData } from "@/types";

const optionalNumber = z.preprocess(v => v === "" || v == null ? undefined : Number(v), z.number().nonnegative().optional());
const schema = z.object({ name: z.string().min(1, "Name is required"), address: z.string().min(1, "Address is required"), city: z.string().min(1, "City is required"), state: z.string().min(2, "State is required"), zip_code: z.string(), zip_plus4: z.string().regex(/^$|^\d{5}-\d{4}$/, "Use 12345-6789"), bedrooms: optionalNumber, bathrooms: optionalNumber, square_footage: optionalNumber, monthly_rent: optionalNumber, description: z.string(), amenities: z.string() });
type FormValues = z.infer<typeof schema>;
interface Props { properties: PropertyData[]; open: boolean; editing: PropertyData | null; saving: boolean; onOpenChange: (v: boolean) => void; onAdd: () => void; onEdit: (p: PropertyData) => void; onDelete: (p: PropertyData) => void; onSave: (values: FormValues) => void; }
const blank: FormValues = { name: "", address: "", city: "", state: "", zip_code: "", zip_plus4: "", bedrooms: undefined, bathrooms: undefined, square_footage: undefined, monthly_rent: undefined, description: "", amenities: "" };
export function PropertiesTab({ properties, open, editing, saving, onOpenChange, onAdd, onEdit, onDelete, onSave }: Props) {
 const { register, handleSubmit, reset, formState: { errors } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: blank });
 useEffect(() => { reset(editing ? { name: editing.name, address: editing.address, city: editing.city, state: editing.state, zip_code: editing.zip_code ?? "", zip_plus4: editing.zip_plus4 ?? "", bedrooms: editing.bedrooms ?? undefined, bathrooms: editing.bathrooms ?? undefined, square_footage: editing.square_footage ?? undefined, monthly_rent: editing.monthly_rent ?? undefined, description: editing.description ?? "", amenities: editing.amenities.join(", ") } : blank); }, [editing, open, reset]);
 return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Properties</h1><p className="mt-1 text-sm text-muted-foreground">Manage the homes protected by fraud monitoring.</p></div><Button onClick={onAdd} className="gap-2"><Plus className="h-4 w-4" />Add property</Button></div>
 <Card className="overflow-hidden shadow-sm"><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Property</TableHead><TableHead>Address</TableHead><TableHead>Beds / Baths</TableHead><TableHead>Sq ft</TableHead><TableHead>Rent</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{properties.map(p => <TableRow key={p.id}><TableCell className="font-medium">{p.name}</TableCell><TableCell className="text-muted-foreground">{p.address}, {p.city}, {p.state}</TableCell><TableCell>{p.bedrooms ?? "—"} / {p.bathrooms ?? "—"}</TableCell><TableCell>{p.square_footage?.toLocaleString() ?? "—"}</TableCell><TableCell>{p.monthly_rent == null ? "—" : `$${p.monthly_rent.toLocaleString()}`}</TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" onClick={() => onEdit(p)} aria-label={`Edit ${p.name}`}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => onDelete(p)} aria-label={`Delete ${p.name}`} className="text-destructive hover:text-destructive"><Trash2 className="h-4 w-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div>{properties.length === 0 && <div className="flex flex-col items-center gap-2 p-12 text-sm text-muted-foreground"><Home className="h-7 w-7" />No properties added yet.</div>}</CardContent></Card>
 <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing ? "Edit property" : "Add property"}</DialogTitle><DialogDescription>Enter the identifying details used to match suspicious listings.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(onSave)} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" error={errors.name?.message}><Input {...register("name")} /></Field><Field label="Address" error={errors.address?.message}><Input {...register("address")} /></Field><Field label="City" error={errors.city?.message}><Input {...register("city")} /></Field><div className="grid grid-cols-2 gap-3"><Field label="State" error={errors.state?.message}><Input maxLength={2} {...register("state")} /></Field><Field label="ZIP"><Input {...register("zip_code")} /></Field></div><Field label="ZIP+4" hint="Building-level match signal for Facebook listings" error={errors.zip_plus4?.message}><Input placeholder="97218-1234" {...register("zip_plus4")} /></Field><Field label="Bedrooms"><Input type="number" step="1" {...register("bedrooms")} /></Field><Field label="Bathrooms"><Input type="number" step="0.5" {...register("bathrooms")} /></Field><Field label="Square feet"><Input type="number" {...register("square_footage")} /></Field><Field label="Monthly rent"><Input type="number" step="0.01" {...register("monthly_rent")} /></Field></div><Field label="Description"><Textarea rows={3} {...register("description")} /></Field><Field label="Amenities" hint="Comma-separated"><Input placeholder="Pool, garage, hardwood floors" {...register("amenities")} /></Field><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save property"}</Button></DialogFooter></form></DialogContent></Dialog></div>;
}
function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: React.ReactNode }) { return <div className="space-y-1.5"><div className="flex items-center justify-between"><Label>{label}</Label>{hint && <span className="text-xs text-muted-foreground">{hint}</span>}</div>{children}{error && <p className="text-xs text-destructive">{error}</p>}</div>; }
export type { FormValues as PropertyFormValues };
